### ISSUE TITLE
Reason for suspending demo?

### ISSUE THREAD

**Issue by BramVanroy** [yukw777/VideoBLIP#2]
Hello

I really like the idea of this repository and I'd like to learn more. Unfortunately I see that you removed the demo. What is the reason behind that? Also, do you have a paper or preprint you could share?

Thanks!

**Comment by fazliimam** [comment]
+1

**Comment by yukw777** [comment]
@BramVanroy @fazlicodes Thanks for your interest and sorry for the late response. I'm actually in the process of releasing the next version very soon, so please stay tuned!

**Comment by fazliimam** [comment]
Hi @yukw777 is it possible for me to know when will it be updated?

**Comment by yukw777** [comment]
@fazlicodes The current plan is after Thanksgiving in December.

**Comment by yukw777** [comment]
Hello everyone, I just released the next version called [EILEV](https://github.com/yukw777/EILEV) with an interactive demo. Please check that out instead!
