### ISSUE TITLE
inference script

### ISSUE THREAD

**Issue by natashamaniarnew** [yukw777/VideoBLIP#3]
Do you have a script for performing inference given a video using the huggingface module

**Comment by yukw777** [comment]
Hi @natashamaniarnew, sorry for the late response. Currently, the best reference script for you would be https://github.com/yukw777/VideoBLIP/blob/7497902051e1a74bf84302a8d7e322efaf851900/demo/app.py. Would it work for you?

**Comment by yukw777** [comment]
I just released a new version called [EILEV](https://github.com/yukw777/EILEV) with a simple sample script that demonstrates how to use VideoBILP: https://github.com/yukw777/EILEV/blob/main/samples/video_blip_generate_action_narration.py
