### ISSUE TITLE
missing 2 required positional arguments in modeling_blip_2.py

### ISSUE THREAD

**Issue by Mu-Yanchen** [yukw777/VideoBLIP#5]
Thanks for your work! When I run the demo/app.py, I met this bug after I using example video in gradio web, the log says:

 ```
 File "/scratch/VideoBLIP-main/app.py", line 39, in respond
    generated_ids = model.generate(
  File "/scratch/anaconda3/envs/blip/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/scratch/transformers-main/src/transformers/models/blip_2/modeling_blip_2.py", line 1800, in generate
    image_embeds = self.vision_model(pixel_values, return_dict=True).last_hidden_state
  File "/scratch/anaconda3/envs/blip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'output_attentions' and 'output_hidden_states'
```

which shows two missing parameters, I think it missing from app.py -> modeling.py ->modeling_blip_2.py but I don't know how to fix this bug and how to get these 2 parameters output(from which module), please inform me if you have any idea

**Comment by yukw777** [comment]
Do you have some custom modification on your copy of `transformers` located in `/scratch/transformers-main/`? `output_attentions` and `output_hidden_states` are not positional arguments in the upstream `transformers`, so I'm not sure what's going on there.

**Comment by Mu-Yanchen** [comment]
Oh, yes. It has something related to my modification in the class VideoBlipVisionModel(Blip2VisionModel), thanks for your help!
