### ISSUE TITLE
how to generate texts based on videos？

### ISSUE THREAD

**Issue by wen020** [yukw777/VideoBLIP#6]
I want to know how to generate texts based on videos？And i only look a chat.

**Comment by yukw777** [comment]
The chat demo generates texts based on videos under the hood, so they're not fundamentally different. Do you have more specific questions?

**Comment by yukw777** [comment]
I just released a new version called [EILEV](https://github.com/yukw777/EILEV) with a simple sample script that demonstrates how to use VideoBILP: https://github.com/yukw777/EILEV/blob/main/samples/video_blip_generate_action_narration.py
