### ISSUE TITLE
Video Summarization

### ISSUE THREAD

**Issue by Jash-the-Mody** [yukw777/VideoBLIP#7]
I was trying to use the model in colab for generating a text summarisation, but didnt know how to. I tried opening the demo, but it hit an error when opening on local host.

while running in collab, it gives an error on model = AutoModelForSeq2SeqLM.from_pretrained("kpyu/video-blip-opt-2.7b-ego4d").

Can you share any notebook doing a similar video analysis task with this model?

**Comment by yukw777** [comment]
I just released a new version called [EILEV](https://github.com/yukw777/EILEV) with a simple sample script that demonstrates how to use VideoBILP: https://github.com/yukw777/EILEV/blob/main/samples/video_blip_generate_action_narration.py
